### ISSUE TITLE
how to scroll up with ngInfiniteScroll for chat pagination

### ISSUE THREAD

**Issue by essivision** [sroze/ngInfiniteScroll#352] opened 2017-01-30 12:54 UTC
Hi,
Please answer this question. I need it very hard.
[http://stackoverflow.com/questions/41936420/how-to-scroll-up-with-nginfinitescroll-for-chat-pagination](http://stackoverflow.com/questions/41936420/how-to-scroll-up-with-nginfinitescroll-for-chat-pagination)

Thanks

**Comment by graingert** [comment] 2017-01-30 14:59
dupe of https://github.com/sroze/ngInfiniteScroll/issues/20 

I don't plan on adding new features. Only bug-fixes.

mdVirtualRepeat can scroll in both directions. Give that directive a go.

**Closed by graingert** 2017-01-30 14:59 UTC
