### ISSUE TITLE
ng-attr-infinite-scroll does not work

### ISSUE THREAD

**Issue by ix-xerri** [sroze/ngInfiniteScroll#275] opened 2016-04-13 15:30 UTC
I am trying to have the scrolling function run after my list, that is shown to the user, loads from the server to avoid an infinite loop if the browser window is big enough (no scrolling is needed). So I am assigning `infinite-scroll` after the list is loaded. My problem is that the command `ng-attr-infinite-scroll`  does not work.

Error: Syntax Error: Token '{' invalid key at column 2 of the expression [{{vm.scroll}}] starting at [{vm.scroll}}].

It works if I remove the `infinite-scroll` dependency.

**Comment by decklord** [comment] 2016-06-05 14:36
You should post some code to look at.

**Comment by graingert** [comment] 2016-07-01 12:41
looks like a dupe of #220

**Closed by graingert** 2016-07-01 12:41 UTC
