### ISSUE TITLE
nextPage() function is firing like infinite times.

### ISSUE THREAD

**Issue by sariyu** [sroze/ngInfiniteScroll#266] opened 2016-03-13 11:57 UTC
![error](https://cloud.githubusercontent.com/assets/14832902/13728511/8797a970-e941-11e5-87cb-99e3131153c9.png)

**Comment by juddey** [comment] 2016-03-15 04:27
I've totally got the same thing. Its firing even when I'm not scrolling.

**Comment by grrseguin** [comment] 2016-03-17 10:31
In waiting the fix, i use the 1.2.1 version.

**Comment by mo3taz-abdallh** [comment] 2016-03-18 17:01
Same Issue

**Comment by joshpierro** [comment] 2016-03-18 21:28
Try adding a height to the container that your list is in

**Comment by timhettler** [comment] 2016-04-01 16:23
I can resolve the issue if I remove the interval from this block:

```
return checkInterval = $interval((function() {
 if (immediateCheck) {
  return handler();
}
}), 0);
```

to:

```
 if (immediateCheck) {
  return handler();
}
```

Otherwise, digest cycles are being called constantly until you trigger the handler.

@sroze, can you explain why this code is wrapped in an `$interval`? This library is essentially unusable in its current state.

**Comment by brandonrobertz** [comment] 2016-04-13 16:52
Agreed with @timhettler ... that $interval is causing all kinds of pain on several scenarios.

**Comment by readme42** [comment] 2016-04-27 11:51
Please mark 1.2.2 as broken, will save many users time!

**Comment by bpcoxjr** [comment] 2016-04-30 02:53
@timhettler is right! I was struggling with this all day while working on a capstone project for my front-end bootcamp and it was firing non-stop. I made the change he indicated and it worked perfectly!

**Comment by fmdcarvalho** [comment] 2016-05-12 17:15
wrap your code in a parent div (or anything with display block) and give it a height:1px. 

If you dont have anything in your container it has no height so it miss calculates the dimension and causes the shouldScroll to be true.

**Comment by thiago-negri** [comment] 2016-05-17 15:46
This was causing my protractor tests to timeout while waiting for synchronization.

Downgrading to 1.2.1 worked.

**Comment by Rahul-Giri** [comment] 2016-06-19 19:33
very true, Downgrading to 1.2.1 worked. please guy do never use 1.2.2. that will make you sick even your mom is top class doctor ;).

**Comment by ajwhite** [comment] 2016-06-22 17:40
Woa - this has been opened for over 3 months? Would consider this a critical issue

**Comment by graingert** [comment] 2016-07-01 12:45
duplicate of #220 (maybe)?

Try 1.3.0.

**Closed by graingert** 2016-07-01 12:45 UTC
