### ISSUE TITLE
Infinite scroll watchers triggers when loaded page is smaller then window size and eats CPU

### ISSUE THREAD

**Issue by Skomantas** [sroze/ngInfiniteScroll#281] opened 2016-05-20 06:51 UTC
Infinite scroll watchers do not cancel loop (triggering) when page size is smaller then window size, even if page is loaded. downgrade to "ngInfiniteScroll": "1.2.1", from  "ngInfiniteScroll":"1.2.2" solves the problem.

**Comment by RELnemtzov** [comment] 2016-05-29 13:56
Having this exact same problem. In my case, I have multiple small "widgets" on a page each with its own infinite-scroll.
CPU is running at 100% after upgrade. Downgrading to 1.2.1 as suggested above restored the expected behavior.

**Comment by rubenCodeforges** [comment] 2016-06-01 14:35
@Skomantas and @RELnemtzov  ive faced same issue even on 1.2.1 the workaround i found is 
to provide a negative value for the `infiniteScrollDistance` : 
```html  
<div infinite-scroll="ctrl.yourMethod()" infinite-scroll-distance="ctrl.simpleVariable">
```
`ctrl is used when you work with controllerAs syntax otherwise $scope style is used`

```javascript
//in controller:
var self = this; //this or use $scope


self.simpleVariable = -1 ;

 //use $timeout to make a 100 millis timeout and switch distance to 1
$timeout(function(){
  self.simpleVariable = 1
}, 100 ) ;

```

This should help , i think there is a bad calculation of the heights and remainings , while distance is used for those calculations we can cheat a bit.

@Skomantas and @RELnemtzov  please reply if it helped

**Comment by thephw** [comment] 2016-06-10 19:51
Also eventually will run out of memory and crash the chrome tab...

**Comment by eugeneware** [comment] 2016-06-20 08:18
This is a huge bug. Our team spent many days trying to source of this. We've pegged our app to the previous version as suggested to fix this. Please fix!

**Comment by rubenCodeforges** [comment] 2016-06-20 11:22
Guys please confirm if my fix did the trick ?

**Comment by neilvana** [comment] 2016-06-22 02:15
@rubenCodeforges, the fix sometimes works for me.  However, based on timing it may still cause issues.  I had to fork the library and add the count=1 argument back on the initial $interval call.  This causes me issues since my infinitely scrolling data may not be infinitely scrolling.  Sometimes my data sets are very large and other times there may only be 1 or 2 records.  In this minimal case the CPU goes crazy forever since "shouldScroll" keeps being true.  I guess that may not have been the intent of this library which is why I didn't submit a pull request.

**Comment by rubenCodeforges** [comment] 2016-06-22 08:36
@neilvana if it sometimes doesnt work , that means you have to increase the timeout millis

```js
$timeout(function(){
  self.simpleVariable = 1;
}, 500 ) ;
```

**Comment by rubenCodeforges** [comment] 2016-06-22 08:37
@eugeneware  we had same issue , hope it will be fixed

**Comment by mebibou** [comment] 2016-06-23 08:48
I just stumble upon this problem too: when profiling the page, I saw some code executed every 10ms that was digesting the page, which seemed insane. When looking down at the code, I saw it was coming from the `$interval` used in the case described here.
Then I looked at the source in the latest release, and on master, and saw that it would be fixed on master here: https://github.com/sroze/ngInfiniteScroll/blob/master/build/ng-infinite-scroll.js#L183

So short story: if you use the version on master, you should be fine, if not, you're screwed. Also, why in hell use a `$interval` to cancel on first iteration? you know `$timeout` is made for that right? please fix and release, this is critical!

**Comment by rubenCodeforges** [comment] 2016-06-23 09:14
@mebibou i hope devs will spot this issue

**Comment by thabemmz** [comment] 2016-06-28 21:12
For me this causes a huge memory leak in my browser as well while switching pages that use `ng-infinite-scroll`, causing some browsers to crash eventually.

What I find surprising is that this issue seems to have been popping up only recently, while the `1.2.2` release was in January. Did anybody experience this issue before the end of May (when this issue was created)?

(it might very well be possible that I didn't catch the memory leak before and this is just strange coincidence, but I wanted to verify).

**Comment by dohomi** [comment] 2016-07-04 10:54
is this issue fixed with `version 1.3`?

**Comment by graingert** [comment] 2016-07-04 10:55
@dohomi should be, try it out.

**Comment by dohomi** [comment] 2016-07-04 12:00
ok I'll do it soon

**Comment by mebibou** [comment] 2016-07-04 13:32
@dohomi yes it is included in the release

**Comment by graingert** [comment] 2016-07-04 13:34
@mebibou ?

**Comment by graingert** [comment] 2016-07-04 15:18
duplicate of https://github.com/sroze/ngInfiniteScroll/issues/235

**Closed by graingert** 2016-07-04 15:18 UTC
